/**
 * @fileOverview Superhero comparison application that allows users to select and compare superhero statistics.
 * This React application fetches superhero data from an API, displays it in a table format,
 * allows users to select two heroes for comparison, and shows detailed stat comparisons.
 * 
 * @author Generated by React Create App
 * @version 1.0.0
 */

import React, { useEffect, useState } from 'react';
import './App.css';

/**
 * Main application component that manages superhero data and comparison functionality.
 * Handles state for superhero list, selected heroes, and view switching between table and comparison views.
 * 
 * @component
 * @returns {JSX.Element} The main application interface
 */
function App() {
  // State management for superhero data and application views
  const [superheroes, setSuperheroes] = useState([]); // Complete list of superhero data from API
  const [selectedHeroes, setSelectedHeroes] = useState([]); // Array of selected heroes (max 2)
  const [currentView, setCurrentView] = useState('table'); // Current view: 'table' or 'comparison'

  // Fetch superhero data from API on component mount
  useEffect(() => {
    fetch('/api/superheroes')
      .then((response) => response.json())
      .then((data) => setSuperheroes(data))
      .catch((error) => console.error('Error fetching superheroes:', error));
  }, []);

  /**
   * Handles the selection and deselection of superheroes for comparison.
   * Manages the logic for selecting up to 2 heroes, with automatic replacement if more are selected.
   * 
   * @param {Object} hero - The superhero object to select/deselect
   * @param {number} hero.id - Unique identifier for the superhero
   * @param {string} hero.name - Name of the superhero
   * @param {Object} hero.powerstats - Power statistics object
   */
  const handleHeroSelection = (hero) => {
    setSelectedHeroes(prev => {
      if (prev.find(h => h.id === hero.id)) {
        // Remove if already selected - toggle off functionality
        return prev.filter(h => h.id !== hero.id);
      } else if (prev.length < 2) {
        // Add if less than 2 selected - normal selection
        return [...prev, hero];
      } else {
        // Replace first selection if 2 already selected - FIFO replacement
        return [prev[1], hero];
      }
    });
  };

  /**
   * Checks if a superhero is currently selected for comparison.
   * 
   * @param {number} heroId - The ID of the hero to check
   * @returns {boolean} True if the hero is selected, false otherwise
   */

  const isHeroSelected = (heroId) => {
    return selectedHeroes.some(h => h.id === heroId);
  };

  /**
   * Switches the view from table to comparison when exactly 2 heroes are selected.
   * Only enables comparison if the selection criteria is met.
   */
  const handleCompare = () => {
    if (selectedHeroes.length === 2) {
      setCurrentView('comparison');
    }
  };

  /**
   * Returns to the table view and clears the selected heroes.
   * Resets the application state for a fresh selection process.
   */
  const handleBackToTable = () => {
    setCurrentView('table');
    setSelectedHeroes([]);
  };

  /**
   * Calculates the winner between two superheroes based on their power statistics.
   * Compares each stat individually and determines overall winner by counting wins.
   * 
   * @param {Object} hero1 - First superhero to compare
   * @param {Object} hero2 - Second superhero to compare
   * @returns {Object} Result object containing winner (or null for tie) and score string
   * @returns {Object|null} returns.winner - The winning hero object or null for ties
   * @returns {string} returns.score - Score in format "X-Y" showing wins for each hero
   */

  const calculateWinner = (hero1, hero2) => {
    // Define all available stats for comparison
    const stats = ['intelligence', 'strength', 'speed', 'durability', 'power', 'combat'];
    let hero1Score = 0;
    let hero2Score = 0;
    
    // Compare each stat and award points to the winner of each category
    stats.forEach(stat => {
      if (hero1.powerstats[stat] > hero2.powerstats[stat]) {
        hero1Score++;
      } else if (hero2.powerstats[stat] > hero1.powerstats[stat]) {
        hero2Score++;
      }
      // Ties in individual stats don't award points to either hero
    });

    // Determine overall winner based on total score
    if (hero1Score > hero2Score) {
      return { winner: hero1, score: `${hero1Score}-${hero2Score}` };
    } else if (hero2Score > hero1Score) {
      return { winner: hero2, score: `${hero2Score}-${hero1Score}` };
    } else {
      return { winner: null, score: `${hero1Score}-${hero2Score}` };
    }
  };

  /**
   * Renders the comparison view showing two selected heroes side by side.
   * Displays hero images, names, detailed stat comparisons, and final results.
   * 
   * @returns {JSX.Element|null} The comparison interface or null if less than 2 heroes selected
   */

  const renderComparison = () => {
    if (selectedHeroes.length !== 2) return null;
    
    // Destructure the two selected heroes for comparison
    const [hero1, hero2] = selectedHeroes;
    const result = calculateWinner(hero1, hero2);
    const stats = ['intelligence', 'strength', 'speed', 'durability', 'power', 'combat'];

    return (
      <div className="comparison-view">
        <button className="back-button" onClick={handleBackToTable}>
          ← Back to Heroes Table
        </button>
        <h1>Superhero Comparison</h1>
        
        <div className="comparison-container">
          <div className="hero-card">
            <img src={hero1.image} alt={hero1.name} className="hero-image" />
            <h2>{hero1.name}</h2>
          </div>
          
          <div className="vs-section">
            <h2>VS</h2>
          </div>
          
          <div className="hero-card">
            <img src={hero2.image} alt={hero2.name} className="hero-image" />
            <h2>{hero2.name}</h2>
          </div>
        </div>

        <div className="stats-comparison">
          {stats.map(stat => {
            // Extract individual stat values for both heroes
            const stat1 = hero1.powerstats[stat];
            const stat2 = hero2.powerstats[stat];
            // Determine which hero wins this specific stat (or if it's a tie)
            const winner = stat1 > stat2 ? 'hero1' : stat1 < stat2 ? 'hero2' : 'tie';
            
            return (
              <div key={stat} className="stat-row">
                <div className={`stat-value ${winner === 'hero1' ? 'winner' : ''}`}>
                  {stat1}
                </div>
                <div className="stat-name">
                  {stat.charAt(0).toUpperCase() + stat.slice(1)}
                </div>
                <div className={`stat-value ${winner === 'hero2' ? 'winner' : ''}`}>
                  {stat2}
                </div>
              </div>
            );
          })}
        </div>

        <div className="final-result">
          <h2>Final Result</h2>
          {result.winner ? (
            <div className="winner-announcement">
              <h3>🏆 {result.winner.name} Wins!</h3>
              <p>Score: {result.score}</p>
            </div>
          ) : (
            <div className="tie-announcement">
              <h3>🤝 It's a Tie!</h3>
              <p>Score: {result.score}</p>
            </div>
          )}
        </div>
      </div>
    );
  };

  /**
   * Renders the main table view displaying all superheroes with selection capabilities.
   * Shows superhero data in a table format with checkboxes for selection and comparison controls.
   * 
   * @returns {JSX.Element} The table interface with superhero data and selection controls
   */
  const renderTable = () => (
    <div className="table-view">
      <h1>Superheroes</h1>
      <div className="selection-info">
        <p>Select 2 superheroes to compare ({selectedHeroes.length}/2 selected)</p>
        {selectedHeroes.length > 0 && (
          <div className="selected-heroes">
            Selected: {selectedHeroes.map(h => h.name).join(', ')}
          </div>
        )}
        <button 
          className="compare-button" 
          onClick={handleCompare}
          disabled={selectedHeroes.length !== 2}
        >
          Compare Heroes
        </button>
      </div>
      
      <table>
        <thead>
          <tr>
            <th>Select</th>
            <th>ID</th>
            <th>Name</th>
            <th>Image</th>
            <th>Intelligence</th>
            <th>Strength</th>
            <th>Speed</th>
            <th>Durability</th>
            <th>Power</th>
            <th>Combat</th>
          </tr>
        </thead>
        <tbody>
          {/* Map through all superheroes and render each as a selectable table row */}
          {superheroes.map((hero) => (
            <tr 
              key={hero.id} 
              className={isHeroSelected(hero.id) ? 'selected-row' : ''}
            >
              <td>
                <input
                  type="checkbox"
                  checked={isHeroSelected(hero.id)}
                  onChange={() => handleHeroSelection(hero)}
                />
              </td>
              <td>{hero.id}</td>
              <td>{hero.name}</td>
              <td><img src={hero.image} alt={hero.name} width="50" /></td>
              <td>{hero.powerstats.intelligence}</td>
              <td>{hero.powerstats.strength}</td>
              <td>{hero.powerstats.speed}</td>
              <td>{hero.powerstats.durability}</td>
              <td>{hero.powerstats.power}</td>
              <td>{hero.powerstats.combat}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );

  return (
    <div className="App">
      <header className="App-header">
        {currentView === 'table' ? renderTable() : renderComparison()}
      </header>
    </div>
  );
}

export default App;
